### PR TITLE
Use Publisher's fallback setting

### PR DESCRIPTION
**Pull request by litzinger**
This is in reference to this support request https://boldminded.com/support/ticket/1378

### CODE REVIEW

**Comment by bjornbjorn** [comment]
Looks good - thanks!

**Comment by macker999** [comment]
hi
the changes do not seem to work correctly
is doesn't seem to work correctly. seo is left blank when switching languages  

eg:  
I have no translations set up for this page just the default english
http://www.eufic.org/en/healthy-living/article/achieving-successful-behaviour-change

If i switch to the german version
http://www.eufic.org/de/healthy-living/article/achieving-successful-behaviour-change

meta title is blank and meta keywords and description are pulling in the default values

i can set up a test site for you?

**Comment by macker999** [comment]
Hi

Could you help me this?  Its affecting our seo and ranking. Thanks

**Comment by litzinger** [comment]
I don't know why the title would be blank and other fields have values, but that doesn't sound like an issue created with my pull request. The other issue you are describing "meta keywords and description are pulling in the default values" sounds like its doing exactly what it is intended to do. If you don't enter meta data for the non-default language it will show the default language values in its place.

**Comment by macker999** [comment]
Hi

Thanks for getting back to me

"The other issue you are describing "meta keywords and description are pulling in the default values" sounds like its doing exactly what it is intended to do. If you don't enter meta data for the non-default language it will show the default language values in its place."

Issue

In this case i have input meta for the default language (english version only)  for this entry

if i switch to the german version  on the front end of the website (we have no german translation created yet) it does not display the title (title is blank) but its pulling the default meta description and keywords NOT from that entries english version meta but from the extension global settings

Brian in boldmind made a change that if there is no translation in the ee admin  and a user switches to the different language in the front end then seo lite should display that entries default meta and title.

I am not sure of this is working correctly 

Its causing us big issues with duplicate content  alerts etc

**Comment by macker999** [comment]
Hi Bjorn

Can you help with this?

**Pull request merged**
